version: "2"
services: 
  # Nginx 1.11.10: https://hub.docker.com/_/nginx/
  web:
    # image: nginx:1.12.1
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
      - 8087:8087
    container_name: web_nginx
    volumes:
      - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./images/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs/nginx:/var/log/nginx
    restart: always